### ISSUE TITLE
Needs way to get notified when parsing has been finished?

### ISSUE THREAD

**Issue by hotohoto** [iTOYS/yes-tail#2]

**Comment by itoys** [comment]
Hi @hotohoto, 
Do you need "end" event if `tail` was run without "follow" option?

**Comment by hotohoto** [comment]
Yes, you're absolutely right. Otherwise, it would be good to be able to get contents synchronously.

**Comment by itoys** [comment]
added in 39ffa7f12c424e602d25b4e47cdfdd2f4c157b7e
